### ISSUE TITLE
安装但显示greenlet找不到

### ISSUE THREAD

**Issue by 4goten** [nicklly/nonebot_plugin_StarRail_calendar#2]
[ERROR] nonebot | Failed to import "nonebot_plugin_starrail_calendar"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\nb\nb\bot.py", line 14, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\Administrator\Desktop\nb\nb\.venv\lib\site-packages\nonebot\plugin\load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\nb\nb\.venv\lib\site-packages\nonebot\plugin\load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\nb\nb\.venv\lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\nb\nb\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\Desktop\nb\nb\.venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\Desktop\nb\nb\.venv\lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\nb\nb\.venv\lib\site-packages\nonebot_plugin_starrail_calendar\__init__.py", line 12, in <module>
    from .draw_calendar import *
  File "C:\Users\Administrator\Desktop\nb\nb\.venv\lib\site-packages\nonebot_plugin_starrail_calendar\draw_calendar.py", line 4, in <module>
    from .browser import get_new_page
  File "C:\Users\Administrator\Desktop\nb\nb\.venv\lib\site-packages\nonebot_plugin_starrail_calendar\browser.py", line 15, in <module>
    from playwright.async_api import Page, Error, Browser, Playwright, async_playwright
  File "C:\Users\Administrator\Desktop\nb\nb\.venv\lib\site-packages\playwright\async_api\__init__.py", line 25, in <module>
    import playwright.async_api._generated
  File "C:\Users\Administrator\Desktop\nb\nb\.venv\lib\site-packages\playwright\async_api\_generated.py", line 25, in <module>
    from playwright._impl._accessibility import Accessibility as AccessibilityImpl
  File "C:\Users\Administrator\Desktop\nb\nb\.venv\lib\site-packages\playwright\_impl\_accessibility.py", line 17, in <module>
    from playwright._impl._connection import Channel
  File "C:\Users\Administrator\Desktop\nb\nb\.venv\lib\site-packages\playwright\_impl\_connection.py", line 34, in <module>
    from greenlet import greenlet
  File "C:\Users\Administrator\Desktop\nb\nb\.venv\lib\site-packages\greenlet\__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
ImportError: DLL load failed while importing _greenlet: 找不到指定的模块。

**Comment by nicklly** [comment]
重新安装playwright试试看

**Comment by 4goten** [comment]
重新安装了指定版本还是不行w

**Comment by nicklly** [comment]
参考 https://blog.csdn.net/weixin_44447793/article/details/124810953 解决方法

**Comment by 4goten** [comment]
找到原因了 差vc的库
