### ISSUE TITLE
命令“星穹日历 status”时报错，怀疑是缺少data.json文件？

### ISSUE THREAD

**Issue by Charxy** [nicklly/nonebot_plugin_StarRail_calendar#3]
安装插件后“星穹日历”“星穹日历 on/off”都能正常运行，但“星穹日历 status”报错。报错信息如下：
```
05-09 13:55:04 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_starrail_calendar) failed.
Traceback (most recent call last):
  File "F:\projects\bot-main\bot.py", line 41, in <module>
    nonebot.run()
  File "E:\Python39\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "E:\Python39\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "E:\Python39\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "E:\Python39\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "E:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "E:\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "E:\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "E:\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "E:\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "E:\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\Python39\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "E:\Python39\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\Python39\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\Python39\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "E:\Python39\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "E:\Python39\lib\site-packages\nonebot_plugin_starrail_calendar\__init__.py", line 156, in _
    group_data[group_id]['server_list'],
KeyError: '922423680'
```
`KeyError`显示的是消息所在的群号。

看了下代码，是不是`__init__.py`的startup里，`for group_id, group_data in load_data('data.json').items()`需要加载`data.json`文件的问题？如果是，请教需要什么样数据框架的json文件，以及应该把文件放在哪里？

**Comment by nicklly** [comment]
已经修复了 请查阅 e4561bd
