### ISSUE TITLE
插件导入失败

### ISSUE THREAD

**Issue by WindraiteLesd** [nicklly/nonebot_plugin_StarRail_calendar#5]
[ERROR] nonebot | Failed to import "nonebot_plugin_starrail_calendar"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Lesdbot\bot.py", line 12, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\ProgramData\miniconda3\lib\site-packages\nonebot\plugin\load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\ProgramData\miniconda3\lib\site-packages\nonebot\plugin\load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\ProgramData\miniconda3\lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "C:\ProgramData\miniconda3\lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\ProgramData\miniconda3\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\ProgramData\miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\ProgramData\miniconda3\lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\ProgramData\miniconda3\lib\site-packages\nonebot_plugin_starrail_calendar\__init__.py", line 12, in <module>
    from .draw_calendar import *
  File "C:\ProgramData\miniconda3\lib\site-packages\nonebot_plugin_starrail_calendar\draw_calendar.py", line 5, in <module>
    from .data_source import *
  File "C:\ProgramData\miniconda3\lib\site-packages\nonebot_plugin_starrail_calendar\data_source.py", line 19, in <module>
    'cn': asyncio.Lock(),
  File "C:\ProgramData\miniconda3\lib\asyncio\locks.py", line 81, in __init__
    self._loop = events.get_event_loop()
  File "C:\ProgramData\miniconda3\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.

**Comment by nicklly** [comment]
重装下playwright 看看？

**Comment by WindraiteLesd** [comment]
> 重装下playwright 看看？

依旧产生该问题

**Comment by nicklly** [comment]
哦 不是playwright 的问题 看起来是异步的问题 python版本是多少呢

**Comment by nicklly** [comment]
3.10.6/9的话我这边是正常的

**Comment by WindraiteLesd** [comment]
> 3.10.6/9的话我这边是正常的

3.9.7，另外补充一下之前刚上商店的时候是正常的，后面不知道怎么回事跟haruka-bot一起出现了类似问题，但haruka我通过降级解决了

**Comment by nicklly** [comment]
> > 3.10.6/9的话我这边是正常的
> 
> 3.9.7，另外补充一下之前刚上商店的时候是正常的，后面不知道怎么回事跟haruka-bot一起出现了类似问题，但haruka我通过降级解决了

升级下python版本试试 不排除是Python 版本的问题

**Comment by WindraiteLesd** [comment]
> > > 3.10.6/9的话我这边是正常的
> > 
> > 
> > 3.9.7，另外补充一下之前刚上商店的时候是正常的，后面不知道怎么回事跟haruka-bot一起出现了类似问题，但haruka我通过降级解决了
> 
> 升级下python版本试试 不排除是Python 版本的问题

之前3.9.7是能用的，出现问题之前没有升级过本插件和python版本，另外我所安装的很多插件不支持python3.10

**Comment by WindraiteLesd** [comment]
bot异常关闭导致的，任务管理器强行结束了一次Python进程，重启好了
